OPEN_AI_MODEL="gpt-4"
REDDIT_SAMPLE_SIZE=25
SAMPLE_TWEETS_FILENAME="tweets-nolinks-nort-noreply.csv"
NUM_TWEETS_TO_SAMPLE=70
NUM_TWEETS_TO_GENERATE=10
PROMPTLAYER_TAG="AutoTweeter"
GOOGLESHEET_WORKSHEETNAME="Sheet1"
GOOGLESHEET_CREDENTIALS_FILE="autotweeter-credentials.json"
